server {
    listen 80;
    server_name tz-systems.online www.tz-systems.online;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
    }

    location / {
        return 301 https://tz-systems.online$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name www.tz-systems.online;

    ssl_certificate /etc/letsencrypt/live/tz-systems.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tz-systems.online/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    return 301 https://tz-systems.online$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name tz-systems.online;

    client_max_body_size 512k;

    ssl_certificate /etc/letsencrypt/live/tz-systems.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tz-systems.online/privkey.pem;
    ssl_session_cache shared:TZSystemsSSL:10m;
    ssl_session_timeout 1d;
    ssl_protocols TLSv1.2 TLSv1.3;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    location / {
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://tz-systems-app:3001;
    }
}
